"""dop mafia penis

Revision ID: 3d937a49565b
Revises: dc7ef94e09ef
Create Date: 2025-05-28 11:28:24.808062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d937a49565b'
down_revision: Union[str, None] = 'dc7ef94e09ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mafia_game', sa.Column('lobby_message_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mafia_game', 'lobby_message_id')
    # ### end Alembic commands ###
