"""Add card buttons support for bunker game

Revision ID: 46c3b84d5e14
Revises: 8052b4d74116
Create Date: 2025-05-31 00:54:49.962872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46c3b84d5e14'
down_revision: Union[str, None] = '8052b4d74116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bunker_player', sa.Column('dm_cards_message_id', sa.BigInteger(), nullable=True))
    op.add_column('bunker_player_card', sa.Column('card_type', sa.String(length=50), nullable=False))
    op.add_column('bunker_player_card', sa.Column('card_name', sa.String(length=255), nullable=False))
    op.alter_column('bunker_player_card', 'card_definition_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bunker_player_card', 'card_definition_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('bunker_player_card', 'card_name')
    op.drop_column('bunker_player_card', 'card_type')
    op.drop_column('bunker_player', 'dm_cards_message_id')
    # ### end Alembic commands ###
