"""init_db

Revision ID: 499e7b34bdfd
Revises: 
Create Date: 2025-06-16 22:14:20.254110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '499e7b34bdfd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bunker_card_definition',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('card_type', sa.String(length=50), nullable=False),
    sa.Column('card_name', sa.String(length=255), nullable=False),
    sa.Column('base_description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('default_is_hidden', sa.Boolean(), nullable=False),
    sa.Column('rarity', sa.String(length=20), nullable=False),
    sa.Column('base_action_effect', sa.JSON(), nullable=True),
    sa.Column('default_activation_condition', sa.String(length=255), nullable=True),
    sa.Column('is_pool_assignable', sa.Boolean(), nullable=False),
    sa.Column('icon_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_name')
    )
    op.create_table('mafia_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.Column('role_description', sa.Text(), nullable=True),
    sa.Column('team', sa.String(length=50), nullable=False),
    sa.Column('is_custom_role', sa.Boolean(), nullable=False),
    sa.Column('abilities', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('time_parse',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp_start', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('birthday', sa.Integer(), nullable=True),
    sa.Column('time_spended_summary', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bunker_card_pool',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pool_name', sa.String(length=100), nullable=False),
    sa.Column('pool_description', sa.Text(), nullable=True),
    sa.Column('is_active_by_default', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pool_name')
    )
    op.create_table('bunker_game',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('category_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('main_voice_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('announcements_text_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('player_cards_text_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('wasteland_voice_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('log_text_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('leader_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.BigInteger(), nullable=True),
    sa.Column('end_time', sa.BigInteger(), nullable=True),
    sa.Column('bunker_capacity', sa.Integer(), nullable=False),
    sa.Column('catastrophe_type', sa.String(length=255), nullable=True),
    sa.Column('survival_duration_years', sa.Integer(), nullable=True),
    sa.Column('bunker_total_area_sqm', sa.Integer(), nullable=True),
    sa.Column('bunker_known_rooms', sa.JSON(), nullable=True),
    sa.Column('secret_room_details', sa.JSON(), nullable=True),
    sa.Column('current_round', sa.Integer(), nullable=False),
    sa.Column('game_settings', sa.JSON(), nullable=True),
    sa.Column('lobby_message_id', sa.BigInteger(), nullable=True),
    sa.Column('leader_controls_message_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['leader_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mafia_game',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('category_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('main_voice_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('main_text_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('mafia_voice_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('cemetery_voice_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('log_text_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('leader_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.BigInteger(), nullable=True),
    sa.Column('end_time', sa.BigInteger(), nullable=True),
    sa.Column('winner_team', sa.String(length=50), nullable=True),
    sa.Column('game_settings', sa.JSON(), nullable=True),
    sa.Column('current_round', sa.Integer(), nullable=False),
    sa.Column('lobby_message_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['leader_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('private_room',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('timestamp_create', sa.BigInteger(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time_counter_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('log_type', sa.Enum('enter', 'exit', name='voicelogtypeenum'), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('parse_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['parse_id'], ['time_parse.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bunker_player',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('is_expelled', sa.Boolean(), nullable=False),
    sa.Column('expulsion_round', sa.Integer(), nullable=True),
    sa.Column('final_status', sa.String(length=50), nullable=True),
    sa.Column('join_time', sa.BigInteger(), nullable=False),
    sa.Column('cards_message_id', sa.BigInteger(), nullable=True),
    sa.Column('dm_cards_message_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['bunker_game.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bunker_pool_assignment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('card_definition_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_definition_id'], ['bunker_card_definition.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pool_id'], ['bunker_card_pool.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mafia_player',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_alive', sa.Boolean(), nullable=False),
    sa.Column('death_night_number', sa.Integer(), nullable=True),
    sa.Column('death_reason', sa.String(length=255), nullable=True),
    sa.Column('personal_voice_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('join_time', sa.BigInteger(), nullable=False),
    sa.Column('leave_time', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['mafia_game.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['mafia_role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mafia_role_setting',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['mafia_game.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['mafia_role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('private_room_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.BigInteger(), nullable=False),
    sa.Column('action_type', sa.Enum('invite', 'kick', 'change', name='privateactiontypeenum'), nullable=False),
    sa.Column('actor', sa.BigInteger(), nullable=False),
    sa.Column('object', sa.BigInteger(), nullable=False),
    sa.Column('before', sa.String(), nullable=True),
    sa.Column('after', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['private_room.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bunker_game_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.Column('actor_player_id', sa.Integer(), nullable=True),
    sa.Column('target_player_id', sa.Integer(), nullable=True),
    sa.Column('target_card_definition_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('action_details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['actor_player_id'], ['bunker_player.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['game_id'], ['bunker_game.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_card_definition_id'], ['bunker_card_definition.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_player_id'], ['bunker_player.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bunker_player_card',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('card_definition_id', sa.Integer(), nullable=True),
    sa.Column('card_type', sa.String(length=50), nullable=False),
    sa.Column('card_name', sa.String(length=255), nullable=False),
    sa.Column('card_name_override', sa.String(length=255), nullable=True),
    sa.Column('card_description_override', sa.Text(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('is_revealed', sa.Boolean(), nullable=False),
    sa.Column('action_effect_details_override', sa.JSON(), nullable=True),
    sa.Column('activation_condition_override', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['card_definition_id'], ['bunker_card_definition.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['bunker_player.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mafia_game_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.Column('phase', sa.String(length=10), nullable=True),
    sa.Column('actor_player_id', sa.Integer(), nullable=True),
    sa.Column('target_player_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('action_details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['actor_player_id'], ['mafia_player.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['mafia_game.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_player_id'], ['mafia_player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('private_room_member',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('room_id', sa.BigInteger(), nullable=False),
    sa.Column('permissions', sa.String(), nullable=True),
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['log_id'], ['private_room_log.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['private_room.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('private_room_member')
    op.drop_table('mafia_game_log')
    op.drop_table('bunker_player_card')
    op.drop_table('bunker_game_log')
    op.drop_table('private_room_log')
    op.drop_table('mafia_role_setting')
    op.drop_table('mafia_player')
    op.drop_table('bunker_pool_assignment')
    op.drop_table('bunker_player')
    op.drop_table('time_counter_log')
    op.drop_table('private_room')
    op.drop_table('mafia_game')
    op.drop_table('bunker_game')
    op.drop_table('bunker_card_pool')
    op.drop_table('user')
    op.drop_table('time_parse')
    op.drop_table('mafia_role')
    op.drop_table('bunker_card_definition')
    # ### end Alembic commands ###
