"""bunker game

Revision ID: 8052b4d74116
Revises: 3d937a49565b
Create Date: 2025-05-31 00:47:24.072768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8052b4d74116'
down_revision: Union[str, None] = '3d937a49565b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bunker_card_definition',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('card_type', sa.String(length=50), nullable=False),
    sa.Column('card_name', sa.String(length=255), nullable=False),
    sa.Column('base_description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('default_is_hidden', sa.Boolean(), nullable=False),
    sa.Column('rarity', sa.String(length=20), nullable=False),
    sa.Column('base_action_effect', sa.JSON(), nullable=True),
    sa.Column('default_activation_condition', sa.String(length=255), nullable=True),
    sa.Column('is_pool_assignable', sa.Boolean(), nullable=False),
    sa.Column('icon_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_name')
    )
    op.create_table('bunker_card_pool',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pool_name', sa.String(length=100), nullable=False),
    sa.Column('pool_description', sa.Text(), nullable=True),
    sa.Column('is_active_by_default', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pool_name')
    )
    op.create_table('bunker_game',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('category_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('main_voice_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('announcements_text_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('player_cards_text_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('wasteland_voice_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('log_text_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('leader_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.BigInteger(), nullable=True),
    sa.Column('end_time', sa.BigInteger(), nullable=True),
    sa.Column('bunker_capacity', sa.Integer(), nullable=False),
    sa.Column('catastrophe_type', sa.String(length=255), nullable=True),
    sa.Column('survival_duration_years', sa.Integer(), nullable=True),
    sa.Column('bunker_total_area_sqm', sa.Integer(), nullable=True),
    sa.Column('bunker_known_rooms', sa.JSON(), nullable=True),
    sa.Column('secret_room_details', sa.JSON(), nullable=True),
    sa.Column('current_round', sa.Integer(), nullable=False),
    sa.Column('game_settings', sa.JSON(), nullable=True),
    sa.Column('lobby_message_id', sa.BigInteger(), nullable=True),
    sa.Column('leader_controls_message_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['leader_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bunker_player',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('is_expelled', sa.Boolean(), nullable=False),
    sa.Column('expulsion_round', sa.Integer(), nullable=True),
    sa.Column('final_status', sa.String(length=50), nullable=True),
    sa.Column('join_time', sa.BigInteger(), nullable=False),
    sa.Column('cards_message_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['bunker_game.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bunker_pool_assignment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('card_definition_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_definition_id'], ['bunker_card_definition.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pool_id'], ['bunker_card_pool.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bunker_game_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.Column('actor_player_id', sa.Integer(), nullable=True),
    sa.Column('target_player_id', sa.Integer(), nullable=True),
    sa.Column('target_card_definition_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('action_details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['actor_player_id'], ['bunker_player.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['game_id'], ['bunker_game.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_card_definition_id'], ['bunker_card_definition.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_player_id'], ['bunker_player.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bunker_player_card',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('card_definition_id', sa.Integer(), nullable=False),
    sa.Column('card_name_override', sa.String(length=255), nullable=True),
    sa.Column('card_description_override', sa.Text(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('is_revealed', sa.Boolean(), nullable=False),
    sa.Column('action_effect_details_override', sa.JSON(), nullable=True),
    sa.Column('activation_condition_override', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['card_definition_id'], ['bunker_card_definition.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['bunker_player.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bunker_player_card')
    op.drop_table('bunker_game_log')
    op.drop_table('bunker_pool_assignment')
    op.drop_table('bunker_player')
    op.drop_table('bunker_game')
    op.drop_table('bunker_card_pool')
    op.drop_table('bunker_card_definition')
    # ### end Alembic commands ###
