"""Initial revision

Revision ID: 848bc52e65cd
Revises: 
Create Date: 2025-01-20 13:34:52.537702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '848bc52e65cd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('birthday', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time_counter_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('log_type', sa.Enum('enter', 'exit', name='voicelogtypeenum'), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('is_parsed', sa.Boolean(), nullable=False, default=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Создание пользователя с id 664752111933718538
    
    op.execute(
        "INSERT INTO public.user (id, tokens, birthday, time_spended_summary) VALUES (664752111933718538, -1, 1090440001, 0)"
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_counter_log')
    op.drop_table('user')
    # ### end Alembic commands ###
