"""Room Members

Revision ID: 976a6a90d7f9
Revises: b72615ab0cb4
Create Date: 2025-01-21 17:32:13.728211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '976a6a90d7f9'
down_revision: Union[str, None] = 'b72615ab0cb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('private_room_member',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('permissions', sa.String(), nullable=True),
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['log_id'], ['private_room_log.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['private_room.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('private_room_log', sa.Column('room_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'private_room_log', 'private_room', ['room_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'private_room_log', type_='foreignkey')
    op.drop_column('private_room_log', 'room_id')
    op.drop_table('private_room_member')
    # ### end Alembic commands ###
