"""mafia update

Revision ID: dc7ef94e09ef
Revises: eaefd8355a83
Create Date: 2025-05-28 10:38:26.811577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc7ef94e09ef'
down_revision: Union[str, None] = 'eaefd8355a83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mafia_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.Column('role_description', sa.Text(), nullable=True),
    sa.Column('team', sa.String(length=50), nullable=False),
    sa.Column('is_custom_role', sa.Boolean(), nullable=False),
    sa.Column('abilities', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('mafia_game',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('category_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('main_voice_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('main_text_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('mafia_voice_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('cemetery_voice_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('log_text_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('leader_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.BigInteger(), nullable=True),
    sa.Column('end_time', sa.BigInteger(), nullable=True),
    sa.Column('winner_team', sa.String(length=50), nullable=True),
    sa.Column('game_settings', sa.JSON(), nullable=True),
    sa.Column('current_round', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['leader_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mafia_player',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_alive', sa.Boolean(), nullable=False),
    sa.Column('death_night_number', sa.Integer(), nullable=True),
    sa.Column('death_reason', sa.String(length=255), nullable=True),
    sa.Column('personal_voice_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('join_time', sa.BigInteger(), nullable=False),
    sa.Column('leave_time', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['mafia_game.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['mafia_role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mafia_role_setting',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['mafia_game.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['mafia_role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mafia_game_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.Column('phase', sa.String(length=10), nullable=True),
    sa.Column('actor_player_id', sa.Integer(), nullable=True),
    sa.Column('target_player_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('action_details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['actor_player_id'], ['mafia_player.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['mafia_game.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_player_id'], ['mafia_player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('private_room_log', sa.Column('actor', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('private_room_log', 'actor')
    op.drop_table('mafia_game_log')
    op.drop_table('mafia_role_setting')
    op.drop_table('mafia_player')
    op.drop_table('mafia_game')
    op.drop_table('mafia_role')
    # ### end Alembic commands ###
