"""change type of id

Revision ID: eaefd8355a83
Revises: 976a6a90d7f9
Create Date: 2025-02-11 12:49:48.383395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaefd8355a83'
down_revision: Union[str, None] = '976a6a90d7f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('private_room', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('private_room_id_seq'::regclass)"))
    op.alter_column('private_room', 'label',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('private_room', 'color',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('private_room', 'icon',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('private_room', 'role_id')
    op.alter_column('private_room_log', 'room_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('private_room_member', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('private_room_member', 'room_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('private_room_member', 'room_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('private_room_member', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('private_room_log', 'room_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.add_column('private_room', sa.Column('role_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.alter_column('private_room', 'icon',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('private_room', 'color',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('private_room', 'label',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('private_room', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('private_room_id_seq'::regclass)"))
    # ### end Alembic commands ###
